### PR TITLE
Update windows compilation instructions

### PR DESCRIPTION
**Pull request by yakobowski**
As suggested in #7, here are updated compilation instructions for Windows. (Well, for the Mingw port.)

There is a bit of a self-fulfilling prophecy here, as of course the automatic installation with Opam does not work yet. What I suggest you do is:
- merge this once you are happy with the README
- make a new release of Apron
- upload a package for this new version in Opam's main repo (https://github.com/ocaml/opam-repository)
- once this is done, it will get propagated automatically to the Windows Opam repo, and I will send a patch to ensure that compilation works under Windows (by adding `-no-cxx` and the patch for perl)

Alternatively, you can add the opam file directly here in Apron's repo, and I can refine it for Windows directly in this PR. This may be slightly simpler in the long term.

(By the way, I noticed inconsistencies in the current opam package: `ocamlbuild` is required but not used, as far I can see, and `conf-gmp`, `conf-mpfr` are missing as dependencies.)

### CODE REVIEW

**Comment by yakobowski** [comment]
Ping :wink: .

**Comment by antoinemine** [comment]
Sorry for the delay. This looks nice, thanks !
Any chance you could propose a modern Opam package that would work for Linux and Windows in Apron's repo, as you seem to know exactly how it needs to be done ? Then we'll pull request to Opam's repo. 
Is the docker-workaround.diff currently in the Apron Opam package still needed ? If so, we could merge it in Apron. It'd be best if Opam could rely directly on a patchless Apron.
conf-gmp and conf mpfr are probably pulled in by mlgmpidl, on which Apron depends for OCaml.

**Comment by nberth** [comment]
@antoinemine I'd suggest first attempting to setup an OPAM package hitting this new repository—instead of custom-made archives as before— that passes the tests of the official repository. I think an adaptation for mingw should be based on that. To proceed we just need to try and merge whatever's waiting in PRs that seems reasonable to make a release, and then create a tag. I'll make the OPAM package then.

I don't think `docker-workaround.diff` is needed anymore, as it was merged some time ago—before the latest release though.

**Comment by yakobowski** [comment]
I will do something based on what Nicolas added in 7ec8164cc81141e737d6ae909efaa3cbef21d930. Would you be okay with adding https://github.com/yakobowski/apron/commit/a4a60ee812decd3f235a1107c5f37756779864e4 directly in this repo? If so, the opam file is almost good. Othewise, we need to attach this additional diff (and move the opam file into a directory).

**Comment by nberth** [comment]
@yakobowski Just out of curiosity did you need to make changes to `mlgmpidl`'s OPAM specification for mingw?

**Comment by yakobowski** [comment]
See https://github.com/yakobowski/opam-repository-mingw/tree/opam2/packages/mlgmpidl/mlgmpidl.1.2.9. I did not do this patch myself, @fdopen added it when he imported the package from the Linux Opam repo.

**Comment by nberth** [comment]
@yakobowski @fdopen Thanks for the link. There's been a bugfix in mlgmpidl since version 1.2.9. But I can probably integrate that patch in the distribution to simplify things.

**Comment by yakobowski** [comment]
ping @antoinemine ;)

**Comment by antoinemine** [comment]
OK, merged!
I intend to review the pending PR and issues in the next few days to see if anything can be fixed quickly. Then do a github release and an "opam publish".
Tell me if there is anything you want done before the release...

**Comment by yakobowski** [comment]
@antoinemine thanks! However, there is one last wrinkle to iron out. You must decide whether you want to include https://github.com/yakobowski/apron/commit/a4a60ee812decd3f235a1107c5f37756779864e4 in the main tree (here).

- If yes, just commit this change as another commit in trunk
- If no, I must tweak the `opam` file to add this patch as a windows-only patch.

I honestly think this can be safely upstreamed : the only case where it would make a difference under Linux is when:
- someone has a certain `perl` in the path when launching `configure`
- change its environment to another `perl`
- and then launches `make`
Not exactly likely. (Plus, you would need the second perl to fail to observe the difference.)

**Comment by antoinemine** [comment]
OK. I merge this as PR #19.

**Comment by yakobowski** [comment]
Thanks @antoinemine! In that case, the last step is to do a release (when convenient for you of course), tu publish it on opam, and I will coordinate with the Opam-mingw maintainer to make sure Apron is marked as installable under Windows.

**Comment by antoinemine** [comment]
Apron 0.9.12 is now released, and published in opam!

**Comment by yakobowski** [comment]
Apron should now be installable under Windows through Opam. (https://github.com/fdopen/opam-repository-mingw/commit/4369bd133de2e02363e288254bd3b9e75a4e1f0f)

**Comment by antoinemine** [comment]
Great thanks !
We could apply the win-specific patch upstream to this repo. 
Do you think it is a good idea? (or it might break something...).

**Comment by yakobowski** [comment]
TBH, I did nothing, this is all the work of @fdopen. I will let him comment whether he wants to see the patch upstreamed here.

**Pull request merged**
